// Pool base de 50 personajes originales del sistema de gacha.
// Estos son fijos (vienen con el bot). El owner puede agregar más con .newchar,
// esos se guardan aparte en data/gachaCustomChars.json y se combinan con este pool en tiempo real.
module.exports = [
  {
    id: "c001",
    name: "Yumi Katsuragi",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 65, defensa: 61, velocidad: 60, carisma: 46 },
    baseValue: 208,
  },
  {
    id: "c002",
    name: "Selene Vance",
    series: "Piratas del Cielo Roto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 35, defensa: 23, velocidad: 45, carisma: 37 },
    baseValue: 80,
  },
  {
    id: "c003",
    name: "Aiko Fujimori",
    series: "Neo Kyoto 2199",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 61, velocidad: 58, carisma: 55 },
    baseValue: 333,
  },
  {
    id: "c004",
    name: "Valeria Nightshade",
    series: "Crónicas de Valdris",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 29, velocidad: 38, carisma: 37 },
    baseValue: 91,
  },
  {
    id: "c005",
    name: "Rin Asakura",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 49, defensa: 55, velocidad: 41, carisma: 62 },
    baseValue: 214,
  },
  {
    id: "c006",
    name: "Ophelia Cross",
    series: "Reino de Aeloria",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 41, velocidad: 36, carisma: 20 },
    baseValue: 117,
  },
  {
    id: "c007",
    name: "Nozomi Sakai",
    series: "Neo Kyoto 2199",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 21, velocidad: 28, carisma: 22 },
    baseValue: 57,
  },
  {
    id: "c008",
    name: "Ithril Moonwhisper",
    series: "Reino de Aeloria",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 54, defensa: 65, velocidad: 44, carisma: 46 },
    baseValue: 269,
  },
  {
    id: "c009",
    name: "Camila Duarte",
    series: "Piratas del Cielo Roto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 33, defensa: 24, velocidad: 44, carisma: 31 },
    baseValue: 58,
  },
  {
    id: "c010",
    name: "Sakura Himura",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 56, defensa: 61, velocidad: 57, carisma: 64 },
    baseValue: 251,
  },
  {
    id: "c011",
    name: "Freya Stormborn",
    series: "Crónicas de Valdris",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 73, defensa: 65, velocidad: 79, carisma: 77 },
    baseValue: 403,
  },
  {
    id: "c012",
    name: "Mika Tanaka",
    series: "Neo Kyoto 2199",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 41, defensa: 39, velocidad: 45, carisma: 28 },
    baseValue: 76,
  },
  {
    id: "c013",
    name: "Lyra Ashworth",
    series: "Reino de Aeloria",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 47, defensa: 53, velocidad: 49, carisma: 51 },
    baseValue: 287,
  },
  {
    id: "c014",
    name: "Xiomara Reyes",
    series: "Piratas del Cielo Roto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 36, defensa: 28, velocidad: 22, carisma: 38 },
    baseValue: 74,
  },
  {
    id: "c015",
    name: "Hana Kobayashi",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 30, defensa: 20, velocidad: 38, carisma: 37 },
    baseValue: 87,
  },
  {
    id: "c016",
    name: "Isolde Draven",
    series: "Crónicas de Valdris",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 61, defensa: 79, velocidad: 68, carisma: 72 },
    baseValue: 620,
  },
  {
    id: "c017",
    name: "Nadia Voss",
    series: "Neo Kyoto 2199",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 51, velocidad: 49, carisma: 54 },
    baseValue: 167,
  },
  {
    id: "c018",
    name: "Elowen Frostgale",
    series: "Reino de Aeloria",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 66, defensa: 66, velocidad: 61, carisma: 68 },
    baseValue: 545,
  },
  {
    id: "c019",
    name: "Bianca Torres",
    series: "Piratas del Cielo Roto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 28, defensa: 29, velocidad: 29, carisma: 31 },
    baseValue: 57,
  },
  {
    id: "c020",
    name: "Yui Nakamura",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 54, defensa: 65, velocidad: 43, carisma: 49 },
    baseValue: 324,
  },
  {
    id: "c021",
    name: "Seraphina Ashe",
    series: "Crónicas de Valdris",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 75, defensa: 83, velocidad: 78, carisma: 84 },
    baseValue: 1782,
  },
  {
    id: "c022",
    name: "Kaori Minamoto",
    series: "Neo Kyoto 2199",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 84, defensa: 87, velocidad: 77, carisma: 80 },
    baseValue: 1221,
  },
  {
    id: "c023",
    name: "Aurelia Windham",
    series: "Reino de Aeloria",
    gender: "waifu", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 95, defensa: 92, velocidad: 96, carisma: 89 },
    baseValue: 3628,
  },
  {
    id: "c024",
    name: "Zephyra Duskmoor",
    series: "Crónicas de Valdris",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 39, velocidad: 37, carisma: 34 },
    baseValue: 57,
  },
  {
    id: "c025",
    name: "Emiko Shirogane",
    series: "Academia Sombraluz",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 65, defensa: 62, velocidad: 76, carisma: 73 },
    baseValue: 675,
  },
  {
    id: "c026",
    name: "Kenji Arata",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 44, defensa: 43, velocidad: 25, carisma: 21 },
    baseValue: 97,
  },
  {
    id: "c027",
    name: "Damian Blackwood",
    series: "Crónicas de Valdris",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 60, defensa: 63, velocidad: 57, carisma: 64 },
    baseValue: 314,
  },
  {
    id: "c028",
    name: "Ryo Fujiwara",
    series: "Neo Kyoto 2199",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 35, defensa: 32, velocidad: 30, carisma: 33 },
    baseValue: 90,
  },
  {
    id: "c029",
    name: "Thaddeus Vane",
    series: "Reino de Aeloria",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 35, velocidad: 25, carisma: 37 },
    baseValue: 99,
  },
  {
    id: "c030",
    name: "Marco Salvatti",
    series: "Piratas del Cielo Roto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 37, velocidad: 21, carisma: 35 },
    baseValue: 61,
  },
  {
    id: "c031",
    name: "Haruto Ishikawa",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 28, velocidad: 28, carisma: 38 },
    baseValue: 70,
  },
  {
    id: "c032",
    name: "Corvin Ashgrave",
    series: "Crónicas de Valdris",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 58, defensa: 41, velocidad: 55, carisma: 41 },
    baseValue: 288,
  },
  {
    id: "c033",
    name: "Sora Kitamura",
    series: "Neo Kyoto 2199",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 43, defensa: 42, velocidad: 36, carisma: 40 },
    baseValue: 80,
  },
  {
    id: "c034",
    name: "Alistair Thorne",
    series: "Reino de Aeloria",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 49, defensa: 61, velocidad: 62, carisma: 51 },
    baseValue: 215,
  },
  {
    id: "c035",
    name: "Diego Fontaine",
    series: "Piratas del Cielo Roto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 24, defensa: 34, velocidad: 26, carisma: 29 },
    baseValue: 60,
  },
  {
    id: "c036",
    name: "Takeshi Mori",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 48, defensa: 47, velocidad: 60, carisma: 57 },
    baseValue: 240,
  },
  {
    id: "c037",
    name: "Ronan Blackthorn",
    series: "Crónicas de Valdris",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 64, defensa: 79, velocidad: 68, carisma: 61 },
    baseValue: 771,
  },
  {
    id: "c038",
    name: "Kaito Yamazaki",
    series: "Neo Kyoto 2199",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 61, defensa: 53, velocidad: 59, carisma: 60 },
    baseValue: 213,
  },
  {
    id: "c039",
    name: "Gideon Ravenscroft",
    series: "Reino de Aeloria",
    gender: "husband", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 98, defensa: 91, velocidad: 90, carisma: 98 },
    baseValue: 2883,
  },
  {
    id: "c040",
    name: "Rafael Contreras",
    series: "Piratas del Cielo Roto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 34, velocidad: 23, carisma: 35 },
    baseValue: 61,
  },
  {
    id: "c041",
    name: "Daiki Segawa",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 24, defensa: 26, velocidad: 41, carisma: 40 },
    baseValue: 66,
  },
  {
    id: "c042",
    name: "Cassius Wynter",
    series: "Crónicas de Valdris",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 78, defensa: 61, velocidad: 73, carisma: 75 },
    baseValue: 787,
  },
  {
    id: "c043",
    name: "Riku Hoshino",
    series: "Neo Kyoto 2199",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 57, defensa: 48, velocidad: 45, carisma: 60 },
    baseValue: 185,
  },
  {
    id: "c044",
    name: "Edmund Faircross",
    series: "Reino de Aeloria",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 52, velocidad: 40, carisma: 60 },
    baseValue: 227,
  },
  {
    id: "c045",
    name: "Santiago Vidal",
    series: "Piratas del Cielo Roto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 45, defensa: 40, velocidad: 23, carisma: 36 },
    baseValue: 91,
  },
  {
    id: "c046",
    name: "Hiroshi Tendo",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 84, defensa: 83, velocidad: 75, carisma: 91 },
    baseValue: 1729,
  },
  {
    id: "c047",
    name: "Draven Ashworth",
    series: "Crónicas de Valdris",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 77, defensa: 85, velocidad: 84, carisma: 83 },
    baseValue: 1261,
  },
  {
    id: "c048",
    name: "Ren Kurogane",
    series: "Neo Kyoto 2199",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 67, defensa: 77, velocidad: 61, carisma: 67 },
    baseValue: 416,
  },
  {
    id: "c049",
    name: "Alaric Nightingale",
    series: "Reino de Aeloria",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 60, defensa: 76, velocidad: 60, carisma: 75 },
    baseValue: 511,
  },
  {
    id: "c050",
    name: "Yusei Amagi",
    series: "Academia Sombraluz",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 64, defensa: 75, velocidad: 66, carisma: 74 },
    baseValue: 743,
  },
];
