// Pool base de 200 personajes reales (animé, películas y videojuegos) del sistema de gacha.
// Estos son fijos (vienen con el bot). El owner puede agregar más con .newchar,
// esos se guardan aparte en data/gachaCustomChars.json y se combinan con este pool en tiempo real.
module.exports = [
  {
    id: "c001",
    name: "Goku",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 99, defensa: 90, velocidad: 98, carisma: 88 },
    baseValue: 3042,
  },
  {
    id: "c002",
    name: "Sailor Moon (Usagi Tsukino)",
    series: "Sailor Moon",
    gender: "waifu", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 97, defensa: 88, velocidad: 94, carisma: 92 },
    baseValue: 2597,
  },
  {
    id: "c003",
    name: "Iron Man (Tony Stark)",
    series: "Marvel",
    gender: "husband", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 91, defensa: 91, velocidad: 92, carisma: 93 },
    baseValue: 3629,
  },
  {
    id: "c004",
    name: "Elsa",
    series: "Frozen",
    gender: "waifu", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 93, defensa: 94, velocidad: 95, carisma: 93 },
    baseValue: 2919,
  },
  {
    id: "c005",
    name: "Geralt de Rivia",
    series: "The Witcher",
    gender: "husband", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 93, defensa: 94, velocidad: 91, carisma: 95 },
    baseValue: 3389,
  },
  {
    id: "c006",
    name: "Wonder Woman (Diana Prince)",
    series: "DC Comics",
    gender: "waifu", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 92, defensa: 91, velocidad: 88, carisma: 92 },
    baseValue: 3620,
  },
  {
    id: "c007",
    name: "Naruto Uzumaki",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 88, defensa: 89, velocidad: 89, carisma: 99 },
    baseValue: 3121,
  },
  {
    id: "c008",
    name: "Mikasa Ackerman",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "mitica",
    rarity: "Mítica",
    stars: 5,
    stats: { poder: 97, defensa: 91, velocidad: 88, carisma: 98 },
    baseValue: 3713,
  },
  {
    id: "c009",
    name: "Monkey D. Luffy",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 85, defensa: 91, velocidad: 78, carisma: 86 },
    baseValue: 1678,
  },
  {
    id: "c010",
    name: "Ichigo Kurosaki",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 76, defensa: 88, velocidad: 77, carisma: 82 },
    baseValue: 1672,
  },
  {
    id: "c011",
    name: "Edward Elric",
    series: "Fullmetal Alchemist",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 79, defensa: 91, velocidad: 81, carisma: 90 },
    baseValue: 1096,
  },
  {
    id: "c012",
    name: "Light Yagami",
    series: "Death Note",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 83, defensa: 91, velocidad: 91, carisma: 81 },
    baseValue: 1427,
  },
  {
    id: "c013",
    name: "Levi Ackerman",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 81, defensa: 83, velocidad: 89, carisma: 75 },
    baseValue: 1322,
  },
  {
    id: "c014",
    name: "Spider-Man (Peter Parker)",
    series: "Marvel",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 84, defensa: 81, velocidad: 91, carisma: 86 },
    baseValue: 1708,
  },
  {
    id: "c015",
    name: "Batman (Bruce Wayne)",
    series: "DC Comics",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 86, defensa: 86, velocidad: 87, carisma: 80 },
    baseValue: 1577,
  },
  {
    id: "c016",
    name: "Kratos",
    series: "God of War",
    gender: "husband", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 87, defensa: 84, velocidad: 89, carisma: 81 },
    baseValue: 1567,
  },
  {
    id: "c017",
    name: "Hinata Hyuga",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 88, defensa: 83, velocidad: 77, carisma: 86 },
    baseValue: 1657,
  },
  {
    id: "c018",
    name: "Nami",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 79, defensa: 92, velocidad: 83, carisma: 83 },
    baseValue: 1229,
  },
  {
    id: "c019",
    name: "Zero Two",
    series: "Darling in the Franxx",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 87, defensa: 82, velocidad: 76, carisma: 91 },
    baseValue: 1659,
  },
  {
    id: "c020",
    name: "Rem",
    series: "Re:Zero",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 81, defensa: 78, velocidad: 76, carisma: 80 },
    baseValue: 1301,
  },
  {
    id: "c021",
    name: "Nezuko Kamado",
    series: "Demon Slayer",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 82, defensa: 80, velocidad: 87, carisma: 90 },
    baseValue: 1718,
  },
  {
    id: "c022",
    name: "Princess Zelda",
    series: "The Legend of Zelda",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 87, defensa: 84, velocidad: 88, carisma: 91 },
    baseValue: 1666,
  },
  {
    id: "c023",
    name: "Lara Croft",
    series: "Tomb Raider",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 78, defensa: 76, velocidad: 80, carisma: 83 },
    baseValue: 1234,
  },
  {
    id: "c024",
    name: "Hermione Granger",
    series: "Harry Potter",
    gender: "waifu", // waifu | husband
    rarityKey: "legendaria",
    rarity: "Legendaria",
    stars: 4,
    stats: { poder: 82, defensa: 76, velocidad: 86, carisma: 79 },
    baseValue: 1004,
  },
  {
    id: "c025",
    name: "Sasuke Uchiha",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 72, defensa: 73, velocidad: 63, carisma: 60 },
    baseValue: 558,
  },
  {
    id: "c026",
    name: "Vegeta",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 75, defensa: 79, velocidad: 68, carisma: 65 },
    baseValue: 438,
  },
  {
    id: "c027",
    name: "Roronoa Zoro",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 64, defensa: 75, velocidad: 74, carisma: 73 },
    baseValue: 455,
  },
  {
    id: "c028",
    name: "Gojo Satoru",
    series: "Jujutsu Kaisen",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 69, defensa: 75, velocidad: 64, carisma: 60 },
    baseValue: 627,
  },
  {
    id: "c029",
    name: "Itachi Uchiha",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 77, defensa: 80, velocidad: 76, carisma: 66 },
    baseValue: 480,
  },
  {
    id: "c030",
    name: "Tanjiro Kamado",
    series: "Demon Slayer",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 72, defensa: 63, velocidad: 76, carisma: 75 },
    baseValue: 695,
  },
  {
    id: "c031",
    name: "Izuku Midoriya",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 63, defensa: 76, velocidad: 75, carisma: 61 },
    baseValue: 747,
  },
  {
    id: "c032",
    name: "All Might",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 80, defensa: 79, velocidad: 64, carisma: 75 },
    baseValue: 414,
  },
  {
    id: "c033",
    name: "Kirito",
    series: "Sword Art Online",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 69, defensa: 62, velocidad: 74, carisma: 71 },
    baseValue: 581,
  },
  {
    id: "c034",
    name: "Cloud Strife",
    series: "Final Fantasy VII",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 74, defensa: 66, velocidad: 67, carisma: 66 },
    baseValue: 535,
  },
  {
    id: "c035",
    name: "Sephiroth",
    series: "Final Fantasy VII",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 79, defensa: 79, velocidad: 69, carisma: 74 },
    baseValue: 724,
  },
  {
    id: "c036",
    name: "Solid Snake",
    series: "Metal Gear Solid",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 68, defensa: 71, velocidad: 73, carisma: 64 },
    baseValue: 727,
  },
  {
    id: "c037",
    name: "Master Chief",
    series: "Halo",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 61, defensa: 65, velocidad: 65, carisma: 62 },
    baseValue: 447,
  },
  {
    id: "c038",
    name: "Thor",
    series: "Marvel",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 71, defensa: 66, velocidad: 78, carisma: 62 },
    baseValue: 715,
  },
  {
    id: "c039",
    name: "Capitán América (Steve Rogers)",
    series: "Marvel",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 67, defensa: 75, velocidad: 61, carisma: 71 },
    baseValue: 650,
  },
  {
    id: "c040",
    name: "Wolverine (Logan)",
    series: "Marvel",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 74, defensa: 64, velocidad: 72, carisma: 78 },
    baseValue: 615,
  },
  {
    id: "c041",
    name: "Harry Potter",
    series: "Harry Potter",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 64, defensa: 75, velocidad: 70, carisma: 74 },
    baseValue: 479,
  },
  {
    id: "c042",
    name: "Aragorn",
    series: "El Señor de los Anillos",
    gender: "husband", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 61, defensa: 75, velocidad: 69, carisma: 78 },
    baseValue: 594,
  },
  {
    id: "c043",
    name: "Sakura Haruno",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 77, defensa: 70, velocidad: 62, carisma: 78 },
    baseValue: 513,
  },
  {
    id: "c044",
    name: "Bulma",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 60, defensa: 70, velocidad: 80, carisma: 74 },
    baseValue: 528,
  },
  {
    id: "c045",
    name: "Nico Robin",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 78, defensa: 62, velocidad: 66, carisma: 67 },
    baseValue: 664,
  },
  {
    id: "c046",
    name: "Rukia Kuchiki",
    series: "Bleach",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 62, defensa: 76, velocidad: 73, carisma: 79 },
    baseValue: 427,
  },
  {
    id: "c047",
    name: "Winry Rockbell",
    series: "Fullmetal Alchemist",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 77, defensa: 76, velocidad: 73, carisma: 68 },
    baseValue: 781,
  },
  {
    id: "c048",
    name: "Asuka Langley",
    series: "Neon Genesis Evangelion",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 71, defensa: 69, velocidad: 63, carisma: 73 },
    baseValue: 446,
  },
  {
    id: "c049",
    name: "Rei Ayanami",
    series: "Neon Genesis Evangelion",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 60, defensa: 64, velocidad: 75, carisma: 65 },
    baseValue: 620,
  },
  {
    id: "c050",
    name: "Misa Amane",
    series: "Death Note",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 62, defensa: 65, velocidad: 80, carisma: 64 },
    baseValue: 667,
  },
  {
    id: "c051",
    name: "Yor Forger",
    series: "Spy x Family",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 62, defensa: 68, velocidad: 68, carisma: 74 },
    baseValue: 530,
  },
  {
    id: "c052",
    name: "Makima",
    series: "Chainsaw Man",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 72, defensa: 69, velocidad: 60, carisma: 68 },
    baseValue: 755,
  },
  {
    id: "c053",
    name: "Asuna",
    series: "Sword Art Online",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 61, defensa: 62, velocidad: 80, carisma: 78 },
    baseValue: 454,
  },
  {
    id: "c054",
    name: "Tifa Lockhart",
    series: "Final Fantasy VII",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 72, defensa: 76, velocidad: 72, carisma: 69 },
    baseValue: 638,
  },
  {
    id: "c055",
    name: "Aerith Gainsborough",
    series: "Final Fantasy VII",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 60, defensa: 61, velocidad: 61, carisma: 74 },
    baseValue: 492,
  },
  {
    id: "c056",
    name: "Chun-Li",
    series: "Street Fighter",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 77, defensa: 61, velocidad: 70, carisma: 63 },
    baseValue: 576,
  },
  {
    id: "c057",
    name: "Samus Aran",
    series: "Metroid",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 78, defensa: 61, velocidad: 78, carisma: 69 },
    baseValue: 672,
  },
  {
    id: "c058",
    name: "Daenerys Targaryen",
    series: "Game of Thrones",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 74, defensa: 75, velocidad: 69, carisma: 71 },
    baseValue: 407,
  },
  {
    id: "c059",
    name: "Katniss Everdeen",
    series: "Los Juegos del Hambre",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 70, defensa: 67, velocidad: 67, carisma: 63 },
    baseValue: 416,
  },
  {
    id: "c060",
    name: "Yoruichi Shihoin",
    series: "Bleach",
    gender: "waifu", // waifu | husband
    rarityKey: "epica",
    rarity: "Épica",
    stars: 3,
    stats: { poder: 65, defensa: 77, velocidad: 75, carisma: 80 },
    baseValue: 593,
  },
  {
    id: "c061",
    name: "Gaara",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 40, defensa: 64, velocidad: 51, carisma: 45 },
    baseValue: 338,
  },
  {
    id: "c062",
    name: "Shikamaru Nara",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 58, defensa: 54, velocidad: 57, carisma: 53 },
    baseValue: 230,
  },
  {
    id: "c063",
    name: "Kakashi Hatake",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 62, defensa: 59, velocidad: 55, carisma: 55 },
    baseValue: 224,
  },
  {
    id: "c064",
    name: "Piccolo",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 59, velocidad: 47, carisma: 41 },
    baseValue: 163,
  },
  {
    id: "c065",
    name: "Trunks",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 48, defensa: 58, velocidad: 57, carisma: 46 },
    baseValue: 313,
  },
  {
    id: "c066",
    name: "Krillin",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 58, defensa: 41, velocidad: 61, carisma: 43 },
    baseValue: 341,
  },
  {
    id: "c067",
    name: "Usopp",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 40, defensa: 53, velocidad: 44, carisma: 57 },
    baseValue: 212,
  },
  {
    id: "c068",
    name: "Sanji",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 60, defensa: 52, velocidad: 46, carisma: 46 },
    baseValue: 222,
  },
  {
    id: "c069",
    name: "Tony Tony Chopper",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 45, velocidad: 54, carisma: 44 },
    baseValue: 284,
  },
  {
    id: "c070",
    name: "Renji Abarai",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 52, defensa: 49, velocidad: 63, carisma: 57 },
    baseValue: 298,
  },
  {
    id: "c071",
    name: "Byakuya Kuchiki",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 47, defensa: 42, velocidad: 48, carisma: 46 },
    baseValue: 293,
  },
  {
    id: "c072",
    name: "Alphonse Elric",
    series: "Fullmetal Alchemist",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 44, defensa: 40, velocidad: 58, carisma: 49 },
    baseValue: 192,
  },
  {
    id: "c073",
    name: "Roy Mustang",
    series: "Fullmetal Alchemist",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 41, defensa: 64, velocidad: 42, carisma: 60 },
    baseValue: 181,
  },
  {
    id: "c074",
    name: "Bakugo Katsuki",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 45, defensa: 62, velocidad: 62, carisma: 40 },
    baseValue: 161,
  },
  {
    id: "c075",
    name: "Todoroki Shoto",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 50, defensa: 45, velocidad: 51, carisma: 63 },
    baseValue: 282,
  },
  {
    id: "c076",
    name: "Eren Yeager",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 60, defensa: 44, velocidad: 59, carisma: 64 },
    baseValue: 244,
  },
  {
    id: "c077",
    name: "Armin Arlert",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 50, defensa: 48, velocidad: 48, carisma: 56 },
    baseValue: 279,
  },
  {
    id: "c078",
    name: "Denji",
    series: "Chainsaw Man",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 51, defensa: 56, velocidad: 62, carisma: 61 },
    baseValue: 301,
  },
  {
    id: "c079",
    name: "Yuji Itadori",
    series: "Jujutsu Kaisen",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 40, defensa: 63, velocidad: 63, carisma: 54 },
    baseValue: 260,
  },
  {
    id: "c080",
    name: "Megumi Fushiguro",
    series: "Jujutsu Kaisen",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 47, defensa: 43, velocidad: 65, carisma: 48 },
    baseValue: 303,
  },
  {
    id: "c081",
    name: "Sung Jin-Woo",
    series: "Solo Leveling",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 48, defensa: 52, velocidad: 51, carisma: 64 },
    baseValue: 153,
  },
  {
    id: "c082",
    name: "Ash Ketchum",
    series: "Pokémon",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 65, defensa: 42, velocidad: 62, carisma: 59 },
    baseValue: 162,
  },
  {
    id: "c083",
    name: "Pikachu",
    series: "Pokémon",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 44, defensa: 55, velocidad: 42, carisma: 60 },
    baseValue: 235,
  },
  {
    id: "c084",
    name: "Luigi",
    series: "Super Mario",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 46, defensa: 62, velocidad: 42, carisma: 45 },
    baseValue: 247,
  },
  {
    id: "c085",
    name: "Sonic",
    series: "Sonic the Hedgehog",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 55, velocidad: 57, carisma: 60 },
    baseValue: 319,
  },
  {
    id: "c086",
    name: "Mega Man",
    series: "Mega Man",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 51, defensa: 50, velocidad: 48, carisma: 48 },
    baseValue: 301,
  },
  {
    id: "c087",
    name: "Ryu",
    series: "Street Fighter",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 63, defensa: 45, velocidad: 48, carisma: 44 },
    baseValue: 342,
  },
  {
    id: "c088",
    name: "Leon S. Kennedy",
    series: "Resident Evil",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 60, defensa: 46, velocidad: 48, carisma: 63 },
    baseValue: 207,
  },
  {
    id: "c089",
    name: "Nathan Drake",
    series: "Uncharted",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 43, defensa: 52, velocidad: 45, carisma: 52 },
    baseValue: 342,
  },
  {
    id: "c090",
    name: "Ezio Auditore",
    series: "Assassin's Creed",
    gender: "husband", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 65, defensa: 51, velocidad: 52, carisma: 48 },
    baseValue: 245,
  },
  {
    id: "c091",
    name: "Temari",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 65, defensa: 56, velocidad: 65, carisma: 48 },
    baseValue: 330,
  },
  {
    id: "c092",
    name: "Ino Yamanaka",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 46, defensa: 58, velocidad: 41, carisma: 44 },
    baseValue: 184,
  },
  {
    id: "c093",
    name: "TenTen",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 44, defensa: 57, velocidad: 64, carisma: 56 },
    baseValue: 270,
  },
  {
    id: "c094",
    name: "Konan",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 53, defensa: 42, velocidad: 60, carisma: 44 },
    baseValue: 153,
  },
  {
    id: "c095",
    name: "Chi-Chi",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 58, velocidad: 63, carisma: 65 },
    baseValue: 246,
  },
  {
    id: "c096",
    name: "Videl",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 42, velocidad: 58, carisma: 56 },
    baseValue: 200,
  },
  {
    id: "c097",
    name: "Android 18",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 43, defensa: 52, velocidad: 59, carisma: 47 },
    baseValue: 314,
  },
  {
    id: "c098",
    name: "Boa Hancock",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 54, defensa: 46, velocidad: 46, carisma: 48 },
    baseValue: 210,
  },
  {
    id: "c099",
    name: "Orihime Inoue",
    series: "Bleach",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 40, defensa: 57, velocidad: 52, carisma: 55 },
    baseValue: 254,
  },
  {
    id: "c100",
    name: "Riza Hawkeye",
    series: "Fullmetal Alchemist",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 49, velocidad: 62, carisma: 44 },
    baseValue: 349,
  },
  {
    id: "c101",
    name: "Ochaco Uraraka",
    series: "My Hero Academia",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 64, defensa: 40, velocidad: 62, carisma: 58 },
    baseValue: 302,
  },
  {
    id: "c102",
    name: "Momo Yaoyorozu",
    series: "My Hero Academia",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 43, defensa: 48, velocidad: 51, carisma: 40 },
    baseValue: 324,
  },
  {
    id: "c103",
    name: "Historia Reiss",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 53, defensa: 44, velocidad: 58, carisma: 45 },
    baseValue: 177,
  },
  {
    id: "c104",
    name: "Annie Leonhart",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 58, defensa: 40, velocidad: 41, carisma: 40 },
    baseValue: 278,
  },
  {
    id: "c105",
    name: "Kaguya Otsutsuki",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 56, defensa: 40, velocidad: 60, carisma: 60 },
    baseValue: 288,
  },
  {
    id: "c106",
    name: "Shinobu Kocho",
    series: "Demon Slayer",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 53, defensa: 41, velocidad: 65, carisma: 60 },
    baseValue: 258,
  },
  {
    id: "c107",
    name: "Mitsuri Kanroji",
    series: "Demon Slayer",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 43, defensa: 45, velocidad: 40, carisma: 51 },
    baseValue: 163,
  },
  {
    id: "c108",
    name: "Toga Himiko",
    series: "My Hero Academia",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 63, velocidad: 52, carisma: 43 },
    baseValue: 216,
  },
  {
    id: "c109",
    name: "Marin Kitagawa",
    series: "My Dress-Up Darling",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 47, defensa: 60, velocidad: 59, carisma: 48 },
    baseValue: 331,
  },
  {
    id: "c110",
    name: "Kagome Higurashi",
    series: "Inuyasha",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 44, defensa: 40, velocidad: 63, carisma: 47 },
    baseValue: 183,
  },
  {
    id: "c111",
    name: "Sakura Kinomoto",
    series: "Card Captor Sakura",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 48, defensa: 51, velocidad: 45, carisma: 53 },
    baseValue: 237,
  },
  {
    id: "c112",
    name: "Misty",
    series: "Pokémon",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 42, defensa: 44, velocidad: 58, carisma: 44 },
    baseValue: 175,
  },
  {
    id: "c113",
    name: "Princess Peach",
    series: "Super Mario",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 53, defensa: 56, velocidad: 52, carisma: 46 },
    baseValue: 259,
  },
  {
    id: "c114",
    name: "Amy Rose",
    series: "Sonic the Hedgehog",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 51, defensa: 60, velocidad: 43, carisma: 45 },
    baseValue: 293,
  },
  {
    id: "c115",
    name: "Cortana",
    series: "Halo",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 63, defensa: 53, velocidad: 51, carisma: 51 },
    baseValue: 236,
  },
  {
    id: "c116",
    name: "Ciri",
    series: "The Witcher",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 59, defensa: 60, velocidad: 52, carisma: 62 },
    baseValue: 347,
  },
  {
    id: "c117",
    name: "Ellie Williams",
    series: "The Last of Us",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 55, defensa: 41, velocidad: 45, carisma: 64 },
    baseValue: 188,
  },
  {
    id: "c118",
    name: "Aloy",
    series: "Horizon Zero Dawn",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 46, defensa: 41, velocidad: 57, carisma: 55 },
    baseValue: 186,
  },
  {
    id: "c119",
    name: "Jill Valentine",
    series: "Resident Evil",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 64, defensa: 62, velocidad: 46, carisma: 40 },
    baseValue: 241,
  },
  {
    id: "c120",
    name: "2B",
    series: "Nier: Automata",
    gender: "waifu", // waifu | husband
    rarityKey: "rara",
    rarity: "Rara",
    stars: 2,
    stats: { poder: 61, defensa: 46, velocidad: 46, carisma: 48 },
    baseValue: 339,
  },
  {
    id: "c121",
    name: "Konohamaru Sarutobi",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 31, velocidad: 40, carisma: 31 },
    baseValue: 69,
  },
  {
    id: "c122",
    name: "Iruka Umino",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 29, defensa: 30, velocidad: 41, carisma: 31 },
    baseValue: 111,
  },
  {
    id: "c123",
    name: "Choji Akimichi",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 26, velocidad: 22, carisma: 44 },
    baseValue: 76,
  },
  {
    id: "c124",
    name: "Kiba Inuzuka",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 23, velocidad: 45, carisma: 34 },
    baseValue: 71,
  },
  {
    id: "c125",
    name: "Shino Aburame",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 32, velocidad: 26, carisma: 31 },
    baseValue: 75,
  },
  {
    id: "c126",
    name: "Rock Lee",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 36, velocidad: 33, carisma: 25 },
    baseValue: 75,
  },
  {
    id: "c127",
    name: "Neji Hyuga",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 34, velocidad: 35, carisma: 35 },
    baseValue: 62,
  },
  {
    id: "c128",
    name: "Jiraiya",
    series: "Naruto",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 42, velocidad: 45, carisma: 32 },
    baseValue: 76,
  },
  {
    id: "c129",
    name: "Yamcha",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 20, defensa: 25, velocidad: 20, carisma: 36 },
    baseValue: 91,
  },
  {
    id: "c130",
    name: "Tien Shinhan",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 30, defensa: 40, velocidad: 39, carisma: 34 },
    baseValue: 87,
  },
  {
    id: "c131",
    name: "Master Roshi",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 31, defensa: 21, velocidad: 43, carisma: 20 },
    baseValue: 53,
  },
  {
    id: "c132",
    name: "Mr. Satan",
    series: "Dragon Ball",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 34, defensa: 41, velocidad: 34, carisma: 30 },
    baseValue: 66,
  },
  {
    id: "c133",
    name: "Franky",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 26, defensa: 26, velocidad: 41, carisma: 22 },
    baseValue: 115,
  },
  {
    id: "c134",
    name: "Brook",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 45, defensa: 24, velocidad: 25, carisma: 43 },
    baseValue: 114,
  },
  {
    id: "c135",
    name: "Jinbe",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 31, defensa: 43, velocidad: 36, carisma: 37 },
    baseValue: 107,
  },
  {
    id: "c136",
    name: "Buggy",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 24, velocidad: 23, carisma: 23 },
    baseValue: 120,
  },
  {
    id: "c137",
    name: "Coby",
    series: "One Piece",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 20, defensa: 22, velocidad: 42, carisma: 31 },
    baseValue: 88,
  },
  {
    id: "c138",
    name: "Uryu Ishida",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 34, velocidad: 22, carisma: 42 },
    baseValue: 64,
  },
  {
    id: "c139",
    name: "Kon",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 23, defensa: 25, velocidad: 22, carisma: 41 },
    baseValue: 58,
  },
  {
    id: "c140",
    name: "Ling Yao",
    series: "Fullmetal Alchemist",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 38, defensa: 43, velocidad: 26, carisma: 30 },
    baseValue: 113,
  },
  {
    id: "c141",
    name: "Maes Hughes",
    series: "Fullmetal Alchemist",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 28, defensa: 22, velocidad: 45, carisma: 21 },
    baseValue: 113,
  },
  {
    id: "c142",
    name: "Iida Tenya",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 23, defensa: 45, velocidad: 39, carisma: 38 },
    baseValue: 71,
  },
  {
    id: "c143",
    name: "Kirishima Eijiro",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 31, defensa: 36, velocidad: 40, carisma: 20 },
    baseValue: 91,
  },
  {
    id: "c144",
    name: "Kaminari Denki",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 45, defensa: 34, velocidad: 35, carisma: 40 },
    baseValue: 61,
  },
  {
    id: "c145",
    name: "Aizawa Shota",
    series: "My Hero Academia",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 28, defensa: 35, velocidad: 44, carisma: 25 },
    baseValue: 55,
  },
  {
    id: "c146",
    name: "Jean Kirstein",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 36, defensa: 22, velocidad: 33, carisma: 39 },
    baseValue: 65,
  },
  {
    id: "c147",
    name: "Connie Springer",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 28, velocidad: 20, carisma: 44 },
    baseValue: 71,
  },
  {
    id: "c148",
    name: "Marco Bodt",
    series: "Attack on Titan",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 34, velocidad: 37, carisma: 20 },
    baseValue: 90,
  },
  {
    id: "c149",
    name: "Toshiro Hitsugaya",
    series: "Bleach",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 29, velocidad: 29, carisma: 36 },
    baseValue: 89,
  },
  {
    id: "c150",
    name: "Gray Fullbuster",
    series: "Fairy Tail",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 35, defensa: 26, velocidad: 24, carisma: 29 },
    baseValue: 90,
  },
  {
    id: "c151",
    name: "Natsu Dragneel",
    series: "Fairy Tail",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 29, velocidad: 44, carisma: 34 },
    baseValue: 104,
  },
  {
    id: "c152",
    name: "Gon Freecss",
    series: "Hunter x Hunter",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 23, defensa: 30, velocidad: 33, carisma: 44 },
    baseValue: 94,
  },
  {
    id: "c153",
    name: "Killua Zoldyck",
    series: "Hunter x Hunter",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 33, defensa: 22, velocidad: 24, carisma: 20 },
    baseValue: 97,
  },
  {
    id: "c154",
    name: "Meliodas",
    series: "Seven Deadly Sins",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 34, defensa: 30, velocidad: 34, carisma: 21 },
    baseValue: 62,
  },
  {
    id: "c155",
    name: "Inuyasha",
    series: "Inuyasha",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 44, velocidad: 25, carisma: 30 },
    baseValue: 115,
  },
  {
    id: "c156",
    name: "Miroku",
    series: "Inuyasha",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 40, defensa: 38, velocidad: 33, carisma: 32 },
    baseValue: 117,
  },
  {
    id: "c157",
    name: "Yugi Muto",
    series: "Yu-Gi-Oh!",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 43, defensa: 26, velocidad: 25, carisma: 24 },
    baseValue: 61,
  },
  {
    id: "c158",
    name: "Joey Wheeler",
    series: "Yu-Gi-Oh!",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 27, velocidad: 28, carisma: 39 },
    baseValue: 90,
  },
  {
    id: "c159",
    name: "Simon",
    series: "Gurren Lagann",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 39, velocidad: 26, carisma: 20 },
    baseValue: 111,
  },
  {
    id: "c160",
    name: "Kamina",
    series: "Gurren Lagann",
    gender: "husband", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 34, defensa: 40, velocidad: 36, carisma: 30 },
    baseValue: 95,
  },
  {
    id: "c161",
    name: "Hanabi Hyuga",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 20, velocidad: 21, carisma: 44 },
    baseValue: 65,
  },
  {
    id: "c162",
    name: "Karin",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 40, defensa: 32, velocidad: 34, carisma: 22 },
    baseValue: 71,
  },
  {
    id: "c163",
    name: "Tsunade",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 43, defensa: 33, velocidad: 44, carisma: 41 },
    baseValue: 62,
  },
  {
    id: "c164",
    name: "Kurenai Yuhi",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 30, defensa: 21, velocidad: 26, carisma: 23 },
    baseValue: 54,
  },
  {
    id: "c165",
    name: "Anko Mitarashi",
    series: "Naruto",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 41, defensa: 27, velocidad: 28, carisma: 29 },
    baseValue: 75,
  },
  {
    id: "c166",
    name: "Mai",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 30, defensa: 39, velocidad: 24, carisma: 23 },
    baseValue: 89,
  },
  {
    id: "c167",
    name: "Launch",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 26, defensa: 40, velocidad: 27, carisma: 31 },
    baseValue: 75,
  },
  {
    id: "c168",
    name: "Marron",
    series: "Dragon Ball",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 28, defensa: 44, velocidad: 35, carisma: 27 },
    baseValue: 63,
  },
  {
    id: "c169",
    name: "Perona",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 34, defensa: 45, velocidad: 36, carisma: 23 },
    baseValue: 66,
  },
  {
    id: "c170",
    name: "Vivi",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 29, velocidad: 23, carisma: 37 },
    baseValue: 80,
  },
  {
    id: "c171",
    name: "Rebecca",
    series: "One Piece",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 26, defensa: 26, velocidad: 22, carisma: 20 },
    baseValue: 76,
  },
  {
    id: "c172",
    name: "Nemu Kurotsuchi",
    series: "Bleach",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 24, velocidad: 23, carisma: 24 },
    baseValue: 81,
  },
  {
    id: "c173",
    name: "Nanao Ise",
    series: "Bleach",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 34, defensa: 38, velocidad: 40, carisma: 39 },
    baseValue: 81,
  },
  {
    id: "c174",
    name: "Ymir",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 42, defensa: 40, velocidad: 45, carisma: 21 },
    baseValue: 98,
  },
  {
    id: "c175",
    name: "Sasha Blouse",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 29, velocidad: 41, carisma: 31 },
    baseValue: 71,
  },
  {
    id: "c176",
    name: "Frieda Reiss",
    series: "Attack on Titan",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 40, defensa: 42, velocidad: 34, carisma: 44 },
    baseValue: 100,
  },
  {
    id: "c177",
    name: "Nobara Kugisaki",
    series: "Jujutsu Kaisen",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 28, defensa: 42, velocidad: 37, carisma: 30 },
    baseValue: 80,
  },
  {
    id: "c178",
    name: "Maki Zenin",
    series: "Jujutsu Kaisen",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 33, defensa: 30, velocidad: 41, carisma: 27 },
    baseValue: 96,
  },
  {
    id: "c179",
    name: "Erza Scarlet",
    series: "Fairy Tail",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 27, defensa: 38, velocidad: 31, carisma: 33 },
    baseValue: 96,
  },
  {
    id: "c180",
    name: "Lucy Heartfilia",
    series: "Fairy Tail",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 23, defensa: 27, velocidad: 21, carisma: 27 },
    baseValue: 120,
  },
  {
    id: "c181",
    name: "Wendy Marvell",
    series: "Fairy Tail",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 26, defensa: 21, velocidad: 24, carisma: 33 },
    baseValue: 75,
  },
  {
    id: "c182",
    name: "Kikyo",
    series: "Inuyasha",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 33, defensa: 21, velocidad: 20, carisma: 27 },
    baseValue: 82,
  },
  {
    id: "c183",
    name: "Sango",
    series: "Inuyasha",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 24, defensa: 30, velocidad: 25, carisma: 23 },
    baseValue: 105,
  },
  {
    id: "c184",
    name: "Rin",
    series: "Inuyasha",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 34, velocidad: 27, carisma: 20 },
    baseValue: 95,
  },
  {
    id: "c185",
    name: "Yui Hirasawa",
    series: "K-On!",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 36, defensa: 42, velocidad: 26, carisma: 27 },
    baseValue: 101,
  },
  {
    id: "c186",
    name: "Mio Akiyama",
    series: "K-On!",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 36, defensa: 27, velocidad: 21, carisma: 36 },
    baseValue: 107,
  },
  {
    id: "c187",
    name: "Emilia",
    series: "Re:Zero",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 32, defensa: 44, velocidad: 42, carisma: 25 },
    baseValue: 71,
  },
  {
    id: "c188",
    name: "Megumin",
    series: "Konosuba",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 43, defensa: 45, velocidad: 39, carisma: 44 },
    baseValue: 63,
  },
  {
    id: "c189",
    name: "Aqua",
    series: "Konosuba",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 40, defensa: 21, velocidad: 43, carisma: 30 },
    baseValue: 73,
  },
  {
    id: "c190",
    name: "Darkness",
    series: "Konosuba",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 29, velocidad: 40, carisma: 23 },
    baseValue: 97,
  },
  {
    id: "c191",
    name: "Violet Evergarden",
    series: "Violet Evergarden",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 29, defensa: 40, velocidad: 38, carisma: 31 },
    baseValue: 104,
  },
  {
    id: "c192",
    name: "Chise Hatori",
    series: "The Ancient Magus' Bride",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 23, defensa: 44, velocidad: 30, carisma: 26 },
    baseValue: 98,
  },
  {
    id: "c193",
    name: "Yuno Gasai",
    series: "Future Diary",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 33, velocidad: 20, carisma: 20 },
    baseValue: 85,
  },
  {
    id: "c194",
    name: "Homura Akemi",
    series: "Madoka Magica",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 33, defensa: 45, velocidad: 29, carisma: 20 },
    baseValue: 62,
  },
  {
    id: "c195",
    name: "Madoka Kaname",
    series: "Madoka Magica",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 25, defensa: 36, velocidad: 44, carisma: 38 },
    baseValue: 111,
  },
  {
    id: "c196",
    name: "Miku Nakano",
    series: "The Quintessential Quintuplets",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 31, defensa: 34, velocidad: 38, carisma: 21 },
    baseValue: 96,
  },
  {
    id: "c197",
    name: "Ichika Nakano",
    series: "The Quintessential Quintuplets",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 29, defensa: 40, velocidad: 40, carisma: 44 },
    baseValue: 111,
  },
  {
    id: "c198",
    name: "Rias Gremory",
    series: "High School DxD",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 22, defensa: 37, velocidad: 23, carisma: 42 },
    baseValue: 119,
  },
  {
    id: "c199",
    name: "Rem Galleu",
    series: "Re:Zero",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 31, defensa: 40, velocidad: 35, carisma: 27 },
    baseValue: 51,
  },
  {
    id: "c200",
    name: "Touka Kirishima",
    series: "Tokyo Ghoul",
    gender: "waifu", // waifu | husband
    rarityKey: "comun",
    rarity: "Común",
    stars: 1,
    stats: { poder: 21, defensa: 45, velocidad: 38, carisma: 20 },
    baseValue: 71,
  },
];
